language: rust
rust:
  - stable
  - beta
  - nightly

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

script:
  # Configure Emacs for building
  - ./autogen.sh
  # TODO: set up makeinfo on travis.
  - ./configure --without-makeinfo --with-xpm=no --with-gif=no
  - make -j 3

  - make check || echo 'make check failed'

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
