---
sudo: required
dist: trusty
language: rust
cache:
  cargo: true
  directories:
    - $HOME/.rustup

rust:
  - nightly

# Run rustfmt first.
stages:
  - rustfmt
  - test
  - cerrors

jobs:
  include:
    - stage: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
      script: ./.travis-format.sh
    - &FULL_TEST
      stage: test
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
      os: linux
      before_script:
        - sudo apt update
        - sudo apt install -y texinfo libgif-dev libxpm-dev
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
      script:
        - ./autogen.sh && RUSTFLAGS="-Dwarnings" ./configure
        - make -j 3 && echo '==> Running tests' && make check
    -
      <<: *FULL_TEST
      os: osx
      env:
        - PATH="/usr/local/opt/texinfo/bin:$PATH"
      before_script:
        # Travis docs say to avoid brew update, but this works around the
        # incorrect Ruby version.
        # https://github.com/travis-ci/travis-ci/issues/8552
        # GNUTLS is now included, no need to explicitly install it.
        - brew update
        - brew install texinfo
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
    - &NO_WINDOW_SYSTEM_TEST
      stage: test
      os: linux
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - TRAVIS_WITH_NO_WINDOW_SYSTEM=1  # So we can tell them apart
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
      script:
        - ./autogen.sh && RUSTFLAGS="-Dwarnings" ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings
        - make -j 3 && echo '==> Running nowindow tests' && make check
    -
      <<: *NO_WINDOW_SYSTEM_TEST
      os: osx
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
    - stage: cerrors
      os: linux  # No need to run this everywhere
      before_script:
        - sudo apt update
        - sudo apt install -y texinfo libgif-dev libxpm-dev
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt-preview
        - ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings --with-gif=no
        - make -C src globals.h
      script:
        - ./.travis-cerrors.sh

notifications:
  fast_finish: true
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
