language: rust
rust:
  - stable
  - beta
  - nightly

script:
  # Test and build the Rust code.
  - cd rust_src
  - cargo test
  - cargo build
  - cd ..

  # Configure Emacs for building
  - ./autogen.sh
  # TODO: set up makeinfo on travis.
  - ./configure --without-makeinfo --with-xpm=no --with-gif=no
  - sed -i "/LIBS_SYSTEM=/c\\LIBS_SYSTEM=-L../rust_src/target/debug -lremacs -ldl" src/Makefile
  - make -j 3

notifications:
  email: false
