language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - texinfo
    - libgif-dev
    - libxpm-dev

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

script:
  # Configure Emacs for building
  - ./autogen.sh
  - ./configure
  - make -j 3

  - make -j 3 check

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
