language: rust
rust:
  - stable
  - beta
  - nightly

script:
  # Test and build the Rust code.
  - cd rust_src
  - cargo test
  - cargo build --release
  - cd ..

  # Configure Emacs for building
  - ./autogen.sh
  - ./configure

notifications:
  email: false
