---
language: rust
cache:
  cargo: true
  directories:
    - $HOME/.rustup

rust:
  - nightly

# Run rustfmt first.
stages:
  - rustfmt
  - test

jobs:
  include:
    - stage: rustfmt
      os: linux  # No need to run this everywhere
      before_script:
        - travis_wait rustup install nightly-2017-10-22
        - rustup default nightly-2017-10-22
        # rustfmt doesn't know where to look for libraries yet.
        # See https://github.com/rust-lang-nursery/rustfmt/issues/1707#issuecomment-310005652
        - export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
        # Install rustfmt-nightly 0.2.12 if it isn't already installed on
        # Travis. This can be slow to install, so raise the Travis timeout.
        - (which rustfmt && rustfmt --version && [[ "$(rustfmt --version)" =~ "0.2.9" ]]) || travis_wait cargo install --force rustfmt-nightly --vers 0.2.9
      script: ./.travis-format.sh
    - &FULL_TEST
      stage: test
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
      os: linux
      before_script:
        - sudo apt install -y texinfo libgif-dev libxpm-dev
      script:
        - ./autogen.sh && ./configure
        - make -j 3 && echo '==> Running tests' && make check
    -
      <<: *FULL_TEST
      os: osx
      env:
        - PATH="/usr/local/opt/texinfo/bin:$PATH"
      before_script:
        # Travis docs say to avoid brew update, but it works around the incorrect Ruby version
        # https://github.com/travis-ci/travis-ci/issues/8552
        - brew update
        - brew install gnutls
        - brew install texinfo
    - &NO_WINDOW_SYSTEM_TEST
      stage: test
      os: linux
      env:
        # Ensure that we build without warnings.
        - CARGO_FLAGS="--features 'strict'"
        - TRAVIS_WITH_NO_WINDOW_SYSTEM=1  # So we can tell them apart
        - TRAVIS_ALLOW_FAILURE=1
      script:
        - ./autogen.sh && ./configure --without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings
        - make -j 3 && echo '==> Running nowindow tests' && make check
    -
      <<: *NO_WINDOW_SYSTEM_TEST
      os: osx
      before_script:
        # Travis docs say to avoid brew update, but it works around the incorrect Ruby version
        - brew update
        - brew install gnutls
        - brew install texinfo
  allow_failures:
    - env: TRAVIS_ALLOW_FAILURE=1

notifications:
  fast_finish: true
  email: false
