language: rust
cache: cargo
rust:
  - 1.14.0
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - texinfo
    - libgif-dev
    - libxpm-dev

env:
  # Ensure that we build without warnings.
  - CARGO_FLAGS="--features 'strict'"

script:
  # Configure Emacs for building
  - ./autogen.sh
  - ./configure
  - make -j 3

  - make -j 3 check

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
  exclude:
    # Since stable is currently 1.14.0, there's no point running 1.14.0 twice.
    # TODO: remove this once 1.15.0 is out.
    - rust: stable
