[package]
name = "remacs-macros"
version = "0.1.0"
description = "Procedural macro used to generate definitions for lisp native functions."

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "0.3"
syn = { version = "0.11.11", features = ["full"] }
synom = "0.11.3"

[dev-dependencies]
syn = { version = "0.11.11", features = ["full"] }
synom = "0.11.3"
