name: Linux standard build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup Rust version
      run: rustup toolchain install $(cat rust-toolchain)
    - name: Install dependencies
      run: sudo apt-get update -y && sudo apt-get install -y texinfo libgif-dev libxmp-dev libgnutls28-dev libgtk-3-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j 3
    - name: make check
      run: make check
